### ISSUE TITLE
/home/appionuser/.XAuthority has root ownership in CentOS7?

### ISSUE THREAD

**Issue by carl9384** [nysbc/appion-protomo#1]
`chown -R appionuser:users /home/appionuser` seems not to work on .XAuthority sometimes on CentOS7. This causes X11 not to forward properly so no graphical programs requiring display can be launched. We'll have to simulate a CentOS7 environment with docker installed to replicate this.

**Comment by alexjnoble** [comment]
I added the following to the end of startup.sh:

chmod 777 /home/appionuser/.Xauthority
chown -R appionuser:users /home/appionuser/.Xauthority

Hopefully that fixes things.
