### ISSUE TITLE
Upload image error

### ISSUE THREAD

**Issue by hongzhan2015** [nysbc/appion-protomo#4]
Dear Alex and all, 
I am trying the appion-protomo with the sample data on my local Mac machine (10.13). I have some errors when I am uploading the image:

uploadSerialEM.py --projectid=2 --session=18sep28x --cs=2 --serialem_stack=/Users/hong/appion-protomo/emg/data/appion/HAslow1.st --serialem_mdoc=/Users/hong/appion-protomo/emg/data/appion/HAslow1.st.mdoc --voltage=200 --description="trial2" --jobtype=uploadimage
 ... Preparing HAslow1 for upload to Appion...
Traceback (most recent call last):
  File "/sw/myami/appion/bin/uploadSerialEM.py", line 130, in <module>
    num_images, info_file, temp_image_dir = serialEM2Appion(options.serialem_stack, options.serialem_mdoc, options.voltage)
  File "/sw/myami/appion/bin/uploadSerialEM.py", line 67, in serialEM2Appion
    stack = mrc.read(stack)
  File "/usr/lib64/python2.7/site-packages/pyami/mrc.py", line 776, in read
    f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/Users/hong/appion-protomo/emg/data/appion/HAslow1.st

Thanks!
Hong

**Comment by hongzhan2015** [comment]
Solved... I forgot to check the path... And binning error still here, I guess it would be fixed next time.

Sorry and thanks!

Hong

**Comment by alexjnoble** [comment]
Hi Hong,

Great! Glad you solved it.

Hope all is well. Best,
-Alex
